### ISSUE TITLE
衡量指标

### ISSUE THREAD

**Issue by xuecheng990531** [callmewenhao/UNet-VOC#1]
请问可以实现IOU，Recall等指标的计算吗，为什么我计算出来的iou一直都是0

**Comment by callmewenhao** [comment]
你好！我添加了 metrics.py，里面有一些常用的评价指标。我之前也出现过IOU为零的情况，原因是代码有问题。

**Comment by callmewenhao** [comment]
想了解图像分割的评价指标，可以看文章：https://zhuanlan.zhihu.com/p/61880018 和 https://zhuanlan.zhihu.com/p/111274912
