### ISSUE TITLE
输出维度问题

### ISSUE THREAD

**Issue by Qiang-Feng98** [callmewenhao/UNet-VOC#2]
你好，我参考了您的代码，这对我的帮助非常大，非常感谢您。
但在测试过程中，发现几个问题，还请您不吝赐教：
1、在VOC数据集上，有20+1分类，所以模型的最后输出通道是24，但您在模型代码中已经将输出固定为：1； 这是为什么呢；
代码：```
class UNET(nn.Module):
    def __init__(
            self, in_channels=3, out_channels=1, features=[64, 128, 256, 512],):
```
2、在进行train（）时，假设设置输出维度是num_class时，那么模型输出shape=（bs, num_class, h, w）,标签的shape = （bs, 1, h, w）,这样计算交叉熵损失函数仍然会出现错误
3、在测试代码的在代码段：
```
    def _fast_hist(self, label_pred, label_true):
        mask = (label_true >= 0) & (label_true < self.num_classes)
        label = self.num_classes * label_true[mask].astype(int) + label_pred[mask]
        count = np.bincount(label , minlength=self.num_classes ** 2)
        hist = count.reshape(self.num_classes, self.num_classes)
        return hist
```
出现错误：TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'
麻烦您能帮我解答一下吗？非常感谢。可以邮件联系1411030449@qq.com，谢谢指正。

**Comment by callmewenhao** [comment]
1. 在VOC数据集上，有20+1分类，所以模型的最后输出通道是**21**；模型model.py中，`out_channels=1`是模型初始化函数的形参默认值，尽管我在训练时会赋新值（如：`model = UNET(in_channels=3, out_channels=21)`），这样写确实会造成误导，我将会改成**21**。
2. 模型输出维度是：`(batchSize, numClass, h, w)`，这个没问题，而标签的维度应该是：`(batchSize, h, w)`，不是`(batchSize, 1， h, w)`。好像是由于`nn.CrossEntropyLoss`会自动帮你把`(batchSize, h, w)`转成维度和输出一致的one-hot向量。
3. 测试代码没太看懂，不过报错似乎是个类型问题🤔。

**Comment by Qiang-Feng98** [comment]
谢谢您的回复，我已经解决了以上的问题：
1. 模型的输出维度是正确的的，我的错误出现在读取标签图片，我使用了Transform.Totensor()函数，这样读出来的标签图的维度是（bs, c, h,w）这无法计算损失函数。
2. 这个报错是因为在计算指标的时候，维度被压缩为一维出现的。
能否问一下，您在训练时，验证集的MeanIOU,FwIOU,Acc,Acc_class指标的数值大约是多少吗？我在训练时，这些指标基本不变，而且MeanIOU=0.09左右最高，这正常吗？也是用的VOC数据集
感谢您的解答，谢谢！

**Comment by callmewenhao** [comment]
我试过**Acc**，**Acc_class**和**MeanIOU**：
-  **Acc**，**Acc_class** 是会随着epoch增加而上升的，我上次训练了200个epoch，**Acc**达到了0.89左右，**Acc_class** 没记住🤣
- **MeanIOU** 也会上升，但是很慢很慢，我i记得不到0.4

**Comment by 1411030449** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    虽然效果还行，但是这些指标太低了，会不会是图片处理方式与指标计算的要求格式有出入呢？
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月11日 ***@***.***> 写道： 




我试过Acc，Acc_class和MeanIOU：



Acc，Acc_class 是会随着epoch增加而上升的，我上次训练了200个epoch，Acc达到了0.89左右，Acc_class 没记住🤣

MeanIOU 也会上升，但是很慢很慢，我i记得不到0.4

**Comment by Qiang-Feng98** [comment]
会不会是图片的处理方式导致的呢？

**Comment by Qiang-Feng98** [comment]
你好，我用你的程序同样迭代了200次，效果却很差很差
![image](https://user-images.githubusercontent.com/54358248/158507618-eaf98f46-8b7a-4225-88ba-c3f69f238448.png)
这是什么原因呢，我找不出原因了

**Comment by callmewenhao** [comment]
1. 这个Demo是我学习Unet时简单写的🤣，有一个缺陷：没在VOC测试集上测试效果！README.md中的预测图片是使用训练集图片做的预测。
2. 我使用测试集上的图片做预测效果和你一样😭，就很差！
3. 我觉得**大概率是训练时间不够**，记得之前有人讨论过VOC训练时间要多久，好像是40h左右，我自己电脑1650Ti训练200epoch也就1.5h，这说明200个epoch远远不够！

**Comment by Qiang-Feng98** [comment]
我用Titan Xp迭代过400次，效果依然不行，不过我是用了单独的测试集，而且训练集和验证集也做了切分，loss一直掉但是各种指标不升，可能是网络太浅，原来想用Unet验证一下指标计算正确与否，没想到卡了好长时间😭

**Comment by callmewenhao** [comment]
我在colab上跑了一下程序，数据集是VOC2012，使用trainval.txt训练，val.txt验证，情况如下图：
![train](https://user-images.githubusercontent.com/54170620/159490167-a2fe8601-8d5d-4bf1-943e-fd25d257e3cd.png)
Acc，Acc_class，mIOU，这些指标都会上升的，只不过一开始 Acc_class，mIOU 上升的很慢，后面就升高了。这说明指标计算应该是正确的。而且这个metrics.py是抄的别人的，应该不会错🤣
总之，谢谢你的交流！👍👏

**Comment by jefferyczl** [comment]
> 我在colab上跑了一下程序，数据集是VOC2012，使用trainval.txt训练，val.txt验证，情况如下图： ![train](https://user-images.githubusercontent.com/54170620/159490167-a2fe8601-8d5d-4bf1-943e-fd25d257e3cd.png) Acc，Acc_class，mIOU，这些指标都会上升的，只不过一开始 Acc_class，mIOU 上升的很慢，后面就升高了。这说明指标计算应该是正确的。而且这个metrics.py是抄的别人的，应该不会错🤣 总之，谢谢你的交流！👍👏

我分析了一下为什么你的accClass精度很高的原因，是因为trainval.txt包含了val.txt的内容，所以Acc_class精度会很高
