### ISSUE TITLE
训练过程中可以加入准确率吗

### ISSUE THREAD

**Issue by Nine9844** [callmewenhao/UNet-VOC#3]
你好，我参考您的代码时发现acc只有在val中计算，如果train中想要计算准确率可以吗？如何添加呢？谢谢

**Comment by callmewenhao** [comment]
其实，我已经写了每10个epoch就进行一次验证的代码（计算模型的 Accuracy），代码如下：
https://github.com/callmewenhao/UNet-VOC/blob/4e6f89cedad0aa12a23b2b573600d1a26362a8c1/train.py#L113-L115
你的意思可能是：在训练完每个batch后进行一次验证。所以，我添加了下面这段代码，对每个batch计算一次 Accuracy：
https://github.com/callmewenhao/UNet-VOC/blob/4e6f89cedad0aa12a23b2b573600d1a26362a8c1/train.py#L28-L38

**Comment by Nine9844** [comment]
好的，谢谢！！！还想问个问题。我在跑train时出现了错误，但是我不清楚如何改，我使用的数据集就是voc数据集
![image](https://user-images.githubusercontent.com/67676862/157786814-6229713f-26f4-498f-bf58-810698cd60dc.png)

**Comment by callmewenhao** [comment]
图片报错的原因是：`resizeMask()`中的`mask.putpalette(p)`中的`p`是空！
resizeMask 函数如下：打开`mask`图片，获取其中的调色板信息，之后把`mask`粘在一张新的位图上，`resize`之后返回；
https://github.com/callmewenhao/UNet-VOC/blob/4e6f89cedad0aa12a23b2b573600d1a26362a8c1/utils.py#L41-L55
`p`是空，**说明你的`mask`图片不是位图，即不带有调色板信息！**
另外：我的注释`输出缩放后的灰度图片`是错的，这个函数一直处理的是位图，输出的也是位图。

**Comment by Nine9844** [comment]
我的mask是位图。也可能是我转成了[0,1]区间的灰度图。是需要mask上带有其他颜色是吗？白色行吗

**Comment by callmewenhao** [comment]
VOC数据集中有个SegmentationClass文件夹，里面放着的图片就是我们的”标签“，也就是`mask`或者叫它`gt`，这些图片是8位彩图（通过调色板显示不同颜色）。如果你把这些图片转成了灰度图，那这大概就是问题所在🤔。
